---

- name: 'INSTALL | Manage repository'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ glusterfs_repositories }}"


- name: 'INSTALL | Manage packages'
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ glusterfs_packages }}"
